name: docs

on:
  workflow_dispatch:
  # uncomment to make it runnable after each push into master
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.10]
        
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          pip install -U mkdocs>=1.6.0 mkdocs-material>=9.5.0 mkdocstrings-python>1.10.0
          
#      - name: Build Docs
#        run: |
#          sphinx-build -b html ./doc/source/ public
#          touch public/.nojekyll
          
#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: public
